### ISSUE TITLE
mail-client/thunderbird-91.7.0 failed

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [c4pp4/gentoo-unity7#11]
I don't know if this is a gentoo issue or a issue with this overlay because i haven't tried merging with default profile.
At first I thought it was because rustfmt USE flag wasn't used on rust-bin (i saw some errors about that) but as it turns out it still errors.
[https://zerobin.net/?76b126648cf6867c#DCBL6NbPKRx2yWXCh3Ilu6b7iNDVKGV2JMeXKv8iOjg=](https://zerobin.net/?76b126648cf6867c#DCBL6NbPKRx2yWXCh3Ilu6b7iNDVKGV2JMeXKv8iOjg=)

**Comment by c4pp4** [comment]
I think it's not an overlay issue.
thunderbird-91.7.0 in my case:
`clang dbus openh264 pulseaudio system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-webp`
`dev-lang/rust-1.58.1`
`sys-devel/clang-13.0.1`

**Comment by c4pp4** [comment]
@sashaaaaaaaaa Did you resolve the problem?
