### ISSUE TITLE
'>=gui-libs/libhandy-1.5.0:1' is masked by overlay, but needed by 'unity-extra/unity-tweak-tool-0.0.7-r220401::gentoo-unity7[bluetooth]'

### ISSUE THREAD

**Issue by renegart** [c4pp4/gentoo-unity7#15]
!!! All ebuilds that could satisfy ">=gui-libs/libhandy-1.5.0:1" have been masked.
!!! One of the following masked packages is required to complete your request:
- gui-libs/libhandy-1.6.2::gentoo (masked by: package.mask)
/etc/portage/package.mask/0000_unity-portage.pmask:
## These are packages maintained via ehooks that must be checked before bump ##

- gui-libs/libhandy-1.6.1::gentoo (masked by: package.mask, ~amd64 keyword)

(dependency required by "gnome-extra/yelp-42.1::gentoo" [ebuild])
(dependency required by "unity-base/ubuntu-docs-16.04.4-r160403::gentoo-unity7" [installed])
(dependency required by "unity-indicators/indicator-session-17.3.20-r211001::gentoo-unity7[help]" [installed])
(dependency required by "unity-indicators/unity-indicators-meta-0-r211001::gentoo-unity7[session]" [installed])
(dependency required by "unity-extra/unity-tweak-tool-0.0.7-r220401::gentoo-unity7[bluetooth]" [installed])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

**Comment by c4pp4** [comment]
Should be fixed in 43c41d2864c6c2bf9e568a14cb712391a2b400e1
