### ISSUE TITLE
'unity-base/unity-build-env' creates broken links

### ISSUE THREAD

**Issue by renegart** [c4pp4/gentoo-unity7#21]
running 'unity-base/unity-build-env' creates broken links.

Link created in /etc/portage/package.accept_keywords: '0000_unity-portage.paccept_keywords -> ../../../profiles/unity-portage.paccept_keywords'

On my system, it has to point to '/home/mirko/git/gentoo-unity7/profiles/unity-portage.paccept_keywords'

**Comment by renegart** [comment]
All links are broken

**Comment by c4pp4** [comment]
Should be fixed via 30fe929b06c718d4871d5f9baf4221c3f7e09557
