### ISSUE TITLE
Proposal to upgrade Unity to 7.6

### ISSUE THREAD

**Issue by RetronEletron** [c4pp4/gentoo-unity7#22]
I've seen that this port still has 7.5 and was wondering if you could upgrade it to the Ubuntu Unity's Upstream 7.6, After doing some research i found out the tree of the release is at https://gitlab.com/ubuntu-unity/unity/unity/-/tree/e7c90e4fad47878161fa9ba4a2aedacada624c1b since tags don't seem to exist there.

**Comment by c4pp4** [comment]
@RetronEletron 
There are no important changes we don't already have.
See https://unity.ubuntuunity.org/blog/unity-7.6/ and https://ubuntuunity.org/blog/ubuntu-unity-22.04/

**Comment by RetronEletron** [comment]
Oh my bad.

**Comment by c4pp4** [comment]
@RetronEletron No problem.
- We have Trash icon controlled via Nemo.
- We backported https://github.com/c4pp4/gentoo-unity7/blob/master/unity-base/unity/files/adjust-broken-app-preview.patch
- We backported:
```
# Replace deprecated function with recommended one #
	sed -i \
		-e "s/gtk_show_uri/gtk_show_uri_on_window/" \
		dash/DashView.cpp || die
```
- There is an USE flag to change theme to unity-yaru. See unity-base/unity-settings[yaru]  - set Ubuntu Unity Yaru as default theme (BTW I don't recommend)
- Default applications see unity-base/unity-meta:
Document Viewer - with Atril
Text Editor - with Pluma
Video Player - with VLC
Image Viewer - with EOM
System Monitor - with MATE System Monitor

**Comment by RetronEletron** [comment]
Impressive.
