### ISSUE TITLE
Two packages compile error and compilation cannot keep going

### ISSUE THREAD

**Issue by firstwaterer** [c4pp4/gentoo-unity7#24]
**>>>Emerging (1 of 10) unity-base/unity-api-8.7-r210402::gentoo-unity7**

...

**[4/11]** /usr/bin/x86_64-pc-linux-gnu-g++ -DUNITY_DLL_EXPORTS -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build/include -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7 -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4  -march=icelake-client -O3 -pipe -finline-functions -fomit-frame-pointer -fvisibility=hidden -std=c++11 -pedantic -Wall -Wextra -fno-permissive -Wsuggest-override -fPIC -MD -MT src/CMakeFiles/unity-api-obj.dir/unity/util/internal/DaemonImpl.cpp.o -MF src/CMakeFiles/unity-api-obj.dir/unity/util/internal/DaemonImpl.cpp.o.d -o src/CMakeFiles/unity-api-obj.dir/unity/util/internal/DaemonImpl.cpp.o -c /var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/internal/DaemonImpl.cpp
FAILED: src/CMakeFiles/unity-api-obj.dir/unity/util/internal/DaemonImpl.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DUNITY_DLL_EXPORTS -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build/include -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7 -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4  -march=icelake-client -O3 -pipe -finline-functions -fomit-frame-pointer -fvisibility=hidden -std=c++11 -pedantic -Wall -Wextra -fno-permissive -Wsuggest-override -fPIC -MD -MT src/CMakeFiles/unity-api-obj.dir/unity/util/internal/DaemonImpl.cpp.o -MF src/CMakeFiles/unity-api-obj.dir/unity/util/internal/DaemonImpl.cpp.o.d -o src/CMakeFiles/unity-api-obj.dir/unity/util/internal/DaemonImpl.cpp.o -c /var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/internal/DaemonImpl.cpp
In file included from /var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/internal/DaemonImpl.cpp:20:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h: In member function ‘R unity::util::ResourcePtr<R, D>::release()’:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:390:20: error: ‘logic_error’ is not a member of ‘std’
  390 |         throw std::logic_error("release() called on ResourcePtr without resource");
      |                    ^~~~~~~~~~~
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:23:1: note: ‘std::logic_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
   22 | #include <mutex>
  +++ |+#include <stdexcept>
   23 | #include <type_traits>
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h: In member function ‘R unity::util::ResourcePtr<R, D>::get() const’:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:433:20: error: ‘logic_error’ is not a member of ‘std’
  433 |         throw std::logic_error("get() called on ResourcePtr without resource");
      |                    ^~~~~~~~~~~
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:433:20: note: ‘std::logic_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/internal/DaemonImpl.cpp: In member function ‘void unity::util::internal::DaemonImpl::close_open_files()’:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/internal/DaemonImpl.cpp:253:46: warning: ignoring attributes on template argument ‘int (*)(DIR*)’ [-Wignored-attributes]
  253 |         ResourcePtr<DIR*, decltype(&closedir)> dir(dirp, closedir);
      |                                              ^

**[5/11]** /usr/bin/x86_64-pc-linux-gnu-g++ -DUNITY_DLL_EXPORTS -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build/include -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7 -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4  -march=icelake-client -O3 -pipe -finline-functions -fomit-frame-pointer -fvisibility=hidden -std=c++11 -pedantic -Wall -Wextra -fno-permissive -Wsuggest-override -fPIC -MD -MT src/CMakeFiles/unity-api-obj.dir/unity/util/FileIO.cpp.o -MF src/CMakeFiles/unity-api-obj.dir/unity/util/FileIO.cpp.o.d -o src/CMakeFiles/unity-api-obj.dir/unity/util/FileIO.cpp.o -c /var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/FileIO.cpp
FAILED: src/CMakeFiles/unity-api-obj.dir/unity/util/FileIO.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DUNITY_DLL_EXPORTS -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7_build/include -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7 -I/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4  -march=icelake-client -O3 -pipe -finline-functions -fomit-frame-pointer -fvisibility=hidden -std=c++11 -pedantic -Wall -Wextra -fno-permissive -Wsuggest-override -fPIC -MD -MT src/CMakeFiles/unity-api-obj.dir/unity/util/FileIO.cpp.o -MF src/CMakeFiles/unity-api-obj.dir/unity/util/FileIO.cpp.o.d -o src/CMakeFiles/unity-api-obj.dir/unity/util/FileIO.cpp.o -c /var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/FileIO.cpp
In file included from /var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/FileIO.cpp:19:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/FileIO.h:34:23: error: ‘uint8_t’ was not declared in this scope
   34 | UNITY_API std::vector<uint8_t> read_binary_file(std::string const& filename);
      |                       ^~~~~~~
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/FileIO.h:26:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   25 | #include <vector>
  +++ |+#include <cstdint>
   26 | 
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/FileIO.h:34:30: error: template argument 1 is invalid
   34 | UNITY_API std::vector<uint8_t> read_binary_file(std::string const& filename);
      |                              ^
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/FileIO.h:34:30: error: template argument 2 is invalid
In file included from /var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/FileIO.cpp:20:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h: In member function ‘R unity::util::ResourcePtr<R, D>::release()’:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:390:20: error: ‘logic_error’ is not a member of ‘std’
  390 |         throw std::logic_error("release() called on ResourcePtr without resource");
      |                    ^~~~~~~~~~~
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:23:1: note: ‘std::logic_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
   22 | #include <mutex>
  +++ |+#include <stdexcept>
   23 | #include <type_traits>
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h: In member function ‘R unity::util::ResourcePtr<R, D>::get() const’:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:433:20: error: ‘logic_error’ is not a member of ‘std’
  433 |         throw std::logic_error("get() called on ResourcePtr without resource");
      |                    ^~~~~~~~~~~
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/ResourcePtr.h:433:20: note: ‘std::logic_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/FileIO.cpp: At global scope:
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/src/unity/util/FileIO.cpp:102:1: error: ambiguating new declaration of ‘std::vector<unsigned char> unity::util::read_binary_file(const std::string&)’
  102 | read_binary_file(string const& filename)
      | ^~~~~~~~~~~~~~~~
/var/tmp/portage/unity-base/unity-api-8.7-r210402/work/unity-api-8.7/include/unity/util/FileIO.h:34:32: note: old declaration ‘int unity::util::read_binary_file(const std::string&)’
   34 | UNITY_API std::vector<uint8_t> read_binary_file(std::string const& filename);
      |                                ^~~~~~~~~~~~~~~~

>**---------------------------------------------------------------------------------------------------------------------------------------**

**>>> Emerging (1 of 1) unity-indicators/indicator-keyboard-0.0.0-r221001::gentoo-unity7**
...
/usr/bin/valac-0.56 --enable-experimental-non-null --metadatadir ../deps --vapidir ../deps --pkg gee-0.8 --pkg posix --pkg pangocairo --pkg gtk+-3.0 --pkg gnome-desktop-3.0 --pkg Xkl-1.0 --pkg Gkbd-3.0 --pkg ibus-1.0 --pkg AccountsService-1.0 --pkg liblightdm-gobject-1   -C main.vala source.vala common.vala ibus-menu.vala ibus-panel.vala indicator-menu.vala keyboard-plugin.vala window-stack.vala unity-session.vala unity-greeter.vala
window-stack.vala:30.2-30.43: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
   30 | 	public abstract string get_app_id_from_pid (uint pid) throws IOError;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                           
window-stack.vala:31.2-31.47: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
   31 | 	public abstract string[] get_window_properties (uint window_id, string app_id, string[] property_names) throws IOError;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                         
window-stack.vala:32.2-32.46: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
   32 | 	public abstract WindowInfo[] get_window_stack () throws IOError;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   
ibus-panel.vala:22.2-22.39: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
   22 | 	public abstract void activate_property (string name, uint state) throws IOError;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                          
ibus-menu.vala:56.8-56.27: warning: `GLib.action_name_is_valid' is deprecated. Use Action.name_is_valid
   56 | 		if (!action_name_is_valid (key)) {
      | 		     ^~~~~~~~~~~~~~~~~~~~         
keyboard-plugin.vala:22.2-22.43: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
   22 | 	public abstract void activate_input_source (uint index) throws IOError;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                             
unity-greeter.vala:22.2-22.40: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
   22 | 	public abstract string get_active_entry () throws IOError;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   
unity-greeter.vala:23.2-23.38: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
   23 | 	public abstract void set_active_entry (string entry_name) throws IOError;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                    
main.vala:327.28-327.51: error: The name `input_sources' does not exist in the context of `Act.User' (AccountsService-1.0)
  327 | 					foreach (var outer in ((!) user).input_sources) {
      | 					                      ^~~~~~~~~~~~~~~~~~~~~~~~   
main.vala:346.21-346.48: error: The name `xkeyboard_layouts' does not exist in the context of `Act.User' (AccountsService-1.0)
  346 | 						var layouts = ((!) user).xkeyboard_layouts;
      | 						              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
main.vala:540.27-540.44: error: The name `input_sources' does not exist in the context of `Act.User' (AccountsService-1.0)
  540 | 				foreach (var outer in user.input_sources) {
      | 				                      ^~~~~~~~~~~~~~~~~~   
main.vala:536.3-536.29: note: `user' was declared here
  536 | 		foreach (var user in users) {
      | 		^~~~~~~~~~~~~~~~~~~~~~~~~~~  
main.vala:559.20-559.41: error: The name `xkeyboard_layouts' does not exist in the context of `Act.User' (AccountsService-1.0)
  559 | 					var layouts = user.xkeyboard_layouts;
      | 					              ^~~~~~~~~~~~~~~~~~~~~~ 
main.vala:536.3-536.29: note: `user' was declared here
  536 | 		foreach (var user in users) {
      | 		^~~~~~~~~~~~~~~~~~~~~~~~~~~  
main.vala:493.19-493.49: warning: `IBus.Bus.list_active_engines' has been deprecated since 1.5.3
  493 | 				var engines = get_ibus ().list_active_engines ();
      | 				              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    
main.vala:1353.17-1353.29: warning: `Posix.SIGTERM' has been deprecated since vala-0.40. Use Posix.Signal.TERM
 1353 | 		Posix.signal (Posix.SIGTERM, (code) => {
      | 		              ^~~~~~~~~~~~~             
Compilation failed: 4 error(s), 10 warning(s)

**Comment by c4pp4** [comment]
@firstwaterer Hi, try to re-emerge `unity-extra/ehooks`. It generates emerge command needed to be applied. Is there any warning message in pkg_postinst phase?

**Comment by firstwaterer** [comment]
unity-indicators/indicator-keyboard build success after executing the following command which is ehooks had notified
emerge -av1 app-admin/system-config-printer dev-libs/glib:2 gnome-base/gnome-desktop:3 gui-libs/libhandy:1 media-fonts/dejavu media-fonts/noto-emoji media-libs/fontconfig:1.0 sys-apps/accountsservice sys-apps/dbus www-client/firefox-bin:rapid x11-libs/vte:2.91

but unity-base/unity-api still gives the same error
here is the full log
[build.log](https://github.com/c4pp4/gentoo-unity7/files/12602708/build.log)
unity-base/unity-api does not apply ehooks' s patch, so there is no any output in pkg_postinst phase...?

**Comment by c4pp4** [comment]
@firstwaterer I've noticed from the build.log you are using unstable gcc 13.2.1 which is not supported yet. I would recommend to downgrade and use stable gcc 12 package.

You have to patch unity-api package to work with gcc 13. According to the error, you need to add `#include <cstdint>` and `#include <stdexcept>` into FileIO.cpp, but maybe there will be more errors after that with the same problem. I will fix it after the gcc 13 stabilization.

**Comment by firstwaterer** [comment]
Uh yes, I merged a new gcc with solt 12, and it built successfully, also this package build failed with llvm 16
It 's necessary to add gcc 12 depend in the ebuild (to avoid the stupid issues like this)

**Comment by firstwaterer** [comment]
but new problem is building compiz

**Comment by firstwaterer** [comment]
[build.log](https://github.com/c4pp4/gentoo-unity7/files/12610406/build.log)
It need to re-build glibmm to process
maybe the gentoo stage3 had installed glibmm already, and it built with glibc 2.34,
maybe add re-build required notifications in ebuild is necessary

**Comment by firstwaterer** [comment]
The next error occurred in [194/894] compiz/compizconfig/libcompizconfig/src/compiz.cpp
[build1.log](https://github.com/c4pp4/gentoo-unity7/files/12610484/build1.log)
Maybe it's caused by this https://github.com/abseil/abseil-cpp/issues/1127
protobuf abseil-cpp installed as depends of package "opencv" and "vlc"
I am trying downgrade those packages with "emerge -uD -v1 '=dev-cpp/abseil-cpp-20211102.0-r2' '=dev-libs/protobuf-21.12'"
hopefully it will be sucess

**Comment by firstwaterer** [comment]
Okay, the it' s no more issues maybe, this issue could be closed.
dev-cpp/abseil-cpp and dev-libs/protobuf should be masked in profile which are dropped c++11

**Comment by c4pp4** [comment]
@firstwaterer 

> to avoid the stupid issues like this

There is a red warning in handbook what testing means, see https://wiki.gentoo.org/wiki/Handbook:X86/Portage/Branches#Testing

> I merged a new gcc

Did you everything what need to be done?
see https://wiki.gentoo.org/wiki/Upgrading_GCC
example:
`emerge -v1 sys-devel/gcc:12`
`gcc-config --list-profiles`
select gcc-12:
`gcc-config <number>`
`source /etc/profile`
`emerge -v1 sys-devel/libtool`
check version:
`gcc --version`
`emerge -v1 sys-devel/llvm sys-devel/clang`
`emerge -ve1 --keep-going @system`
`emerge -ve1 --keep-going @world`

After that rebuild all from gentoo-unity7:
`emerge -v1 gentoolkit`
`emerge -v1 --keep-going $(equery l -F '$cp' *::gentoo-unity7)`

**Comment by c4pp4** [comment]
And of course after the successful rebuild from the previous post, install unity: `emerge -v unity-meta`
