### ISSUE TITLE
Emerging the package gives an error in the start and fails at keyboard-indicator

### ISSUE THREAD

**Issue by aanjaneya-meaow** [c4pp4/gentoo-unity7#28]
Hey there! Here's another issue I noticed. I've attached the entire output:

[logs.txt](https://github.com/c4pp4/gentoo-unity7/files/14895940/logs.txt)

**Comment by c4pp4** [comment]
Thank you for the report. There are two errors in the logfile.
1) unity-scopes/smart-scopes error:
    unity-scopes/smart-scopes-7-r211003::gentoo-unity7 failed (depend phase):
                                                        *   distutils_enable_tests: unsupported argument: nose

    It's fixed now. (cab7712)

2) unity-indicators/indicator-session error:
    error: The name \`input_sources' does not exist in the context of `Act.User' (AccountsService-1.0)

    Run `emerge gentoo-unity-env` and read warning message. I think you didn't rebuild sys-apps/accountsservice.
