### ISSUE TITLE
unity-indicators/indicator-session Fails to compile

### ISSUE THREAD

**Issue by RetronEletron** [c4pp4/gentoo-unity7#3]
Hello i love this fork but over the whole install one package managed to get me dead anyways.

LOG:

https://pastebin.com/Vg6PNw2F

Please get back when solution or something :D.

**Comment by c4pp4** [comment]
It looks like you don't have 'dev-util/gdbus-codegen' package installed. Can you check it?

**Comment by RetronEletron** [comment]
Hello yes it is installed

**Comment by RetronEletron** [comment]
Nvm fixed closing the issue

**Comment by c4pp4** [comment]
@RetronEletron What was the issue, please?

**Comment by RetronEletron** [comment]
Oh the package seemed to always fail so i just gave up

**Comment by c4pp4** [comment]
@RetronEletron Can you pastebin.com the output of :
`emerge -av1 MYCMAKEARGS="-DCMAKE_FIND_DEBUG_MODE=ON" emerge -av1 indicator-session`

**Comment by RetronEletron** [comment]
Great time actually i will come back to you but i may had accidently deleted the partition as i gave up so ye.

**Comment by RetronEletron** [comment]
Hello i'm back and i ran this command and i got 100% gdbus-codegen installed anyways.

LOG:
https://pastebin.com/vAmzS4Zu

**Comment by c4pp4** [comment]
@RetronEletron 
Do you have installed `dev-util/cmake-extras` package?

**Comment by RetronEletron** [comment]
I do not

**Comment by RetronEletron** [comment]
THANKS SO MUCH AFTER INSTALLING IT, IT WORKED JUST FINE :))

**Comment by c4pp4** [comment]
@RetronEletron 
> I WILL REMEMBER THIS NEXT TIME

You don't need to, I've fixed it.
